version: "3.9"
services:
  client:
    build:
      context: client
    ports:
      - 1234:3000

  server-demo1:
    build:
      context: server
    command: npm run start:demo1
    ports:
      - 13001:13001

  server-demo2:
    build:
      context: server
    command: npm run start:demo2
    ports:
      - 13002:13002

  server-demo3:
    build:
      context: server
    command: npm run start:demo3
    ports:
      - 13003:13003

  server-demo4:
    build:
      context: server
    command: npm run start:demo4
    ports:
      - 13004:13004

  server-demo5:
    build:
      context: server
    command: npm run start:demo5
    ports:
      - 13005:13005

  server-demo6:
    build:
      context: server
    command: npm run start:demo6
    ports:
      - 13006:13006

  server-demo7:
    build:
      context: server
    command: npm run start:demo7
    ports:
      - 13007:13007

  envoy-grpc-proxy:
    image: envoyproxy/envoy:latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 9211:9211
      - 9901:9901

